### ISSUE TITLE
Speech-to-Text API - potential parsing issue: `by_speaker` parameter treated as string Instead of boolean

### ISSUE THREAD

**Issue by WilliamBonvini** [JigsawStack/jigsawstack-python#18]
Hi,

I’m encountering an issue with the Speech-to-Text API where it seems like the server is interpreting a boolean parameter as a string, resulting in a 400 Bad Request error.

Here’s the relevant snippet of my code:
```python
from jigsawstack import JigsawStack

jigsaw = JigsawStack()

params = {
    "file_store_key": "tmp.mp3",
    "language": "it",
    "by_speaker": True,  # Boolean value passed here
}

response = jigsaw.audio.speech_to_text(params)
```

When I make a POST request to the /ai/transcribe endpoint with the above parameters, I get the following error response:

```json
{
  "error": [
    {
      "code": "invalid_type",
      "path": [
        "by_speaker"
      ],
      "message": "Expected boolean, received string",
      "expected": "boolean",
      "received": "string"
    }
  ],
  "message": "Bad request",
  "success": false
}
```

I’ve double-checked my code, and I am passing by_speaker as a boolean (True). However, the server seems to be interpreting it as a string instead.

#### Additional Server Log Details:
* API Endpoint: https://api.jigsawstack.com/v1/ai/transcribe
* Query Parameters: file_store_key=tmp.mp3&language=it&by_speaker=true
* HTTP Method: POST
* Response Status: 400 Bad Request
* Content-Type: application/json
* Auth Method: API Key
* Agent: python-requests/2.32.3

Thank you for looking into this!

**Comment by iamNarcisse** [comment]
@WilliamBonvini, Pushed a fix https://github.com/JigsawStack/jigsawstack-python/pull/19.  Thanks for flagging this!

**Comment by iamNarcisse** [comment]
@WilliamBonvini fix release [here](https://github.com/JigsawStack/jigsawstack-python/releases/tag/v0.1.13)
